name: CSAPP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Execute Codes
      run: |
        cd ./lab1
        chmod a+x ./*
        touch test.txt
        chmod 777 test.txt
        for i in `ls -al .`; do if [ -f $i ];then ./$i; fi; done
  job-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install dependencies
      run: |
        sudo apt-get install gcc-multilib
    - name: Execute Codes
      run: |
        set -x
        cd ./lab2/datalab-handout
        make
        ./btest -T 50
        result=`./btest -T 50 | grep "Total point" | cut -d " " -f3 | cut -d "/" -f1`
        ddl=`date -d "2022-10-09 15:59" +%s --utc`
        current_time=`date +%s`
        [ $current_time -le $ddl ]
        [ $result -ge 36 ]
  job-3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Execute Codes
      run: |
       set -x
       ans=0
       cd ./lab3/bomb-handout
       for i in `seq 70`
       do
          if [ -d "$i" ]; then
            cd ./$i;
            ./bomb answer.txt;
            if [ ! $? -eq 0 ]; then
              echo "$? is not correct"
            elsif
              echo "$i is corrent"
              let ans+=1
            fi
          fi
        done
        [ $ans -eq 70 ]
